### ISSUE TITLE
gather basic royalty free assets for card images (raider waite is public domain) add a table for these images to the database

### ISSUE THREAD

**Issue by sydneyrd** [KLaw47/tarottime-server#8]
Add images to the ERD and database

**Comment by DanPurdon** [comment]
https://github.com/nashville-software-school/bangazon-llc/blob/main/book-2-levelup/chapters/GR_UPLOADS.md

**Comment by DanPurdon** [comment]
https://github.com/sydneyrd/gamecapstoneserver/blob/master/gamecapstoneapi/models/image.py

**Comment by DanPurdon** [comment]
Notes for testing: 
After pipenv shell and install,
python3 manage.py migrate
python3 manage.py loaddata card_images
Create superuser (python3 manage.py createsuperuser)
Run server, open in browser, navigate to /admin
Log in with superuser
Verify Card imgs exist in TAROTTIMEAPI
Verify you can now upload images

In VScode, verify there is now a "media" folder with a subdirectory called card_images containing 79 images (78 cards and one cardback)
You can also view the card_image.py model, which uses Django's fancy ImageField
